name: Docker CI
on: [push, pull_request]
jobs:
  pipeline:
    name: RedisCachePOCClient pipeline
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
    timeout-minutes: 40
    env:
      NODE_VERSION: 16.17.0
      JHI_DISABLE_WEBPACK_LOGS: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.17.0
      - name: Install node.js packages
        run: npm install
      - name: Package application
        run: npm run build
      - name: Build and publish docker image
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
        run: |
          GIT_TAG=:${GITHUB_REF#refs/tags/}
          DOCKER_TAG=${GIT_TAG#:refs/heads/main}
          ./mvnw -ntp jib:build -Djib.to.image=jhipster/redis-cache-poc-client${DOCKER_TAG} -Djib.to.auth.username="${{secrets.DOCKER_USERNAME }}" -Djib.to.auth.password="${{secrets.DOCKER_TOKEN }}" -Pprod
